# 공통 JPA 설정
spring:
  jpa:
    database: mysql
    show-sql: ${JPA_SHOW_SQL}
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
  datasource:
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:3}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
