# 공통 JWT 설정
constants:
  jwt:
    issuer: fairwayops-auth-service
    bearer-format: Bearer
    claim-key: role
    secret-key: ${JWT_SECRET_KEY}
    access-token:
      name: access-token
      expiration-seconds: 3600 #1시간
    refresh-token:
      name: refresh-token
      expiration-seconds: 1209600 #14일

security:
  jwt:
    secret: ${constants.jwt.secret-key}
    access-token-expiration: 3600000 #1시간
    refresh-token-expiration: 1209600000 #14일
